### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by soshimee** [Pecacheu/Elevators-v2#26]
```
[22:36:53 ERROR]: Could not pass event SignChangeEvent to Elevators v3.3.4
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.type.WallSign (org.bukkit.craftbukkit.v1_19_R1.block.data.CraftBlockData and org.bukkit.block.data.type.WallSign are in unnamed module of loader java.net.URLClassLoader @18769467)
        at net.forestfire.elevators.Conf.getSignBlock(Conf.java:260) ~[100823 - Elevators.jar:?]
        at net.forestfire.elevators.Conf.addSignBlock(Conf.java:268) ~[100823 - Elevators.jar:?]
        at net.forestfire.elevators.Main.onSignChange(Main.java:115) ~[100823 - Elevators.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1004.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:git-petal-"eb64b15"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3687) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$32(ServerGamePacketListenerImpl.java:3637) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1491) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by PizzaBoxx3** [comment]
Got the same message

**Comment by Pecacheu** [comment]
Version for 1.21.3 works in 1.19.X
