### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by aryanny** [Pecacheu/Elevators-v2#27]
it seems that the elevator plugin wont load but i have an error message from the console

```
05.01 12:41:28 [Server] Server thread/INFO Enabling Elevators v3.3.4
05.01 12:41:28 [Server] Server thread/ERROR Error occurred while enabling Elevators v3.3.4 (Is it up to date?)
05.01 12:41:28 [Server] INFO java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
05.01 12:41:28 [Server] INFO at net.forestfire.elevators.Main.onEnable(Main.java:40) ~[?:?]
05.01 12:41:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
05.01 12:41:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
05.01 12:41:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
05.01 12:41:28 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3624-Spigot-d90018e-ab1586c]
05.01 12:41:28 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
05.01 12:41:28 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
05.01 12:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
05.01 12:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
05.01 12:41:28 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
```

**Comment by PecorinoDev** [comment]
Same, I hope this plugin will be updated to the latest version soon enough.

**Comment by notqtcris** [comment]
update?

**Comment by Pecacheu** [comment]
Version for 1.21.3 works in 1.19.X
