### ISSUE TITLE
1.20.2 Compatibility 

### ISSUE THREAD

**Issue by IngeniousCoder** [Pecacheu/Elevators-v2#29]
Would like to check if there is compatibility with 1.20.2?

Also noticing this issue consistently happening:

[12:36:36] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to Elevators v3.3.4
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "net.forestfire.elevators.Conf.CALL" is null
	at net.forestfire.elevators.Main.onBlockPhysics(Main.java:173) ~[Elevators-3.3.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor394.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-223]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-223]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-223]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.redstone.NeighborUpdater.executeUpdate(NeighborUpdater.java:59) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:137) ~[?:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:45) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1884) ~[?:?]
	at net.minecraft.world.level.block.BaseRailBlock.onRemove(BaseRailBlock.java:128) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1201) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:460) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:946) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:907) ~[?:?]
	at net.minecraft.world.level.block.DetectorRailBlock.checkPressed(DetectorRailBlock.java:99) ~[?:?]
	at net.minecraft.world.level.block.DetectorRailBlock.entityInside(DetectorRailBlock.java:50) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1213) ~[?:?]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1603) ~[paper-1.20.2.jar:git-Paper-223]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.ReflectionInvoker$ReflectionMethodInvoker.invokeVA(ReflectionInvoker.java:127) ~[BKCommonLib-1.20.2-v1-1634.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.ReflectionInvoker.invoke(ReflectionInvoker.java:77) ~[BKCommonLib-1.20.2-v1-1634.jar:?]
	at com.bergerkiller.generated.net.minecraft.world.entity.EntityHandle$impl.checkBlockCollisions(Unknown Source) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.moveImpl(EntityMoveHandler.java:194) ~[BKCommonLib-1.20.2-v1-1634.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.move(EntityMoveHandler.java:160) ~[BKCommonLib-1.20.2-v1-1634.jar:?]
	at com.bergerkiller.bukkit.common.controller.EntityController.onMove(EntityController.java:168) ~[BKCommonLib-1.20.2-v1-1634.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:2266) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable.onPhysicsPostMove(MinecartMemberRideable.java:111) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:2034) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1836) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:37) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at com.bergerkiller.bukkit.tc.controller.global.TrainUpdateController$TrainUpdateTask.run(TrainUpdateController.java:225) ~[TrainCarts-1.20.2-v1-1464.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-223]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-223]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:36:36] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to Elevators v3.3.4
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "net.forestfire.elevators.Conf.CALL" is null

**Comment by IngeniousCoder** [comment]
Any updates avail?

**Comment by Runkang10** [comment]
Just click the iron block to start move in the floor that you selected.

**Comment by IngeniousCoder** [comment]
Intermittently does not work for some players. 

Clicked with empty hand.

**Comment by Pecacheu** [comment]
Hmm I would guess it's some change to the API for the BlockPhysicsEvent. I will look into this when I can, my dev environment hasn't been setup as I moved PCs and haven't done Minecraft plugin dev in a while.

**Comment by IngeniousCoder** [comment]
Ok, thanks. Hope can get resolution soon :)

**Comment by IngeniousCoder** [comment]
Hihi, any recent updates?

**Comment by Runkang10** [comment]
Can I fork this and reformat in to Kotlin and upgrade entire source code?

**Comment by Pecacheu** [comment]
Interesting, I didn't know you could make mods in Kotlin like you can with Android apps.

If you want to fix it I would prefer if you do a pull request and keep it in Java, but you can fork it if you want. I still haven't had the chance to work on it since I've been working on other non-Minecraft projects in my free time but I do want to get back to this (and the weird Novation Launchpad elevator control plugin that went with it cause that was a fun side thing)

**Comment by Pecacheu** [comment]
Now updated for 1.21.3 (I only tested 1.21.X and 1.19.X but it should work in 1.20.X)
